name: Create Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # This is required to create a release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: create Executable
      id: create-executable # This is required to reference the output of this step
      uses: sayyid5416/pyinstaller@v1
      with:
        python-ver: '3.12'
        spec: 'main.py'
        upload_exe_with_name: 'main.exe'
        options: --onefile
        
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./dist/**
